version: '3.3'

services:
  backend_python:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    ports:
      - 28282:8080

  backend_php:
    build:
      context: ./backend/php
      dockerfile: Dockerfile
    volumes:
      - ./backend/php/.composer_cache:/root/composer/
    ports:
      - 18181:8181